/* You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde" Output: "e"
Example 2:
Input: s = "", t = "y" Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters. */

function findDifference(s: string, t: string) {
  let diff = 0;

  for (let i = 0; i < t.length; i++) {
    diff = +t.charCodeAt(i);

    if (i < s.length) {
      diff -= s.charCodeAt(i);
    }
  }

  return String.fromCharCode(diff);
}

function findDifference2(s: string, t: string) {
  let ch = 0;

  // XOR all the characters of both s and t.
  for (let i = 0; i < s.length; i += 1) {
    ch ^= s.charCodeAt(i);
  }
  for (let i = 0; i < t.length; i += 1) {
    ch ^= t.charCodeAt(i);
  }

  // What is left after XORing everything is the difference.
  return String.fromCharCode(ch);
}

function findDifference3(s: string, t: string): string {
  // Create frequency maps for both strings
  const frequencyMapS: Map<string, number> = new Map();
  const frequencyMapT: Map<string, number> = new Map();

  // Populate frequency map for string s
  for (const char of s) {
    frequencyMapS.set(char, (frequencyMapS.get(char) || 0) + 1);
  }

  // Populate frequency map for string t
  for (const char of t) {
    frequencyMapT.set(char, (frequencyMapT.get(char) || 0) + 1);
  }

  // Find the character with a frequency difference
  for (const char of frequencyMapT.keys()) {
    if (frequencyMapT.get(char) !== frequencyMapS.get(char)) {
      return char;
    }
  }

  return "";
}

console.log(findDifference("abcd", "abcde"));
console.log(findDifference2("13", "123"));
console.log(findDifference3("", "y"));
